---
language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images


before_script:
  - image="coverage:build"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh -t utc -t cve-2014--shellshock "$image"

after_script:
  - docker images
