---
language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

script:
  - docker build -t "coverage:build" .
  - ~/official-images/test/run.sh "coverage:build"

after_script:
  - docker images
